/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thewalkingtec.poo.loginFolder;

/**
 *
 * @author mathiasviquez
 */
public class CrearComponentes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearComponentes.class.getName());

    /**
     * Creates new form CrearComponentes
     */
    public CrearComponentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbdPnCrearComponente = new javax.swing.JTabbedPane();
        pnlZombie = new javax.swing.JPanel();
        btnCrearZombie = new javax.swing.JButton();
        txtFldRangeZombie = new javax.swing.JTextField();
        lblRangeZombie = new javax.swing.JLabel();
        lblAppearanceZombie = new javax.swing.JLabel();
        txtFldAppearanceZombie = new javax.swing.JTextField();
        lblZombieImageOutput2 = new javax.swing.JLabel();
        lblFieldsZombie = new javax.swing.JLabel();
        txtFldFieldsZombie = new javax.swing.JTextField();
        txtFldDamageZombie = new javax.swing.JTextField();
        lblDamageZombie = new javax.swing.JLabel();
        cmbBxTypeZombie = new javax.swing.JComboBox<>();
        lblTypeZombie = new javax.swing.JLabel();
        txtFldLifeZombie = new javax.swing.JTextField();
        lblLifeZombie = new javax.swing.JLabel();
        lblZombieImageOutput1 = new javax.swing.JLabel();
        lblImageZombie2 = new javax.swing.JLabel();
        txtFldImageZombie2 = new javax.swing.JTextField();
        txtFldImageZombie1 = new javax.swing.JTextField();
        lblImageZombie1 = new javax.swing.JLabel();
        txtFldZombie = new javax.swing.JTextField();
        lblNameZombie = new javax.swing.JLabel();
        pnlBloque = new javax.swing.JPanel();
        btnCrearBloque = new javax.swing.JButton();
        lblAppearanceBloque = new javax.swing.JLabel();
        txtFldAppearanceBloque = new javax.swing.JTextField();
        lblBloqueImageOutput2 = new javax.swing.JLabel();
        lblFieldsBloque = new javax.swing.JLabel();
        txtFldFieldsBloque = new javax.swing.JTextField();
        txtFldDamageBloque = new javax.swing.JTextField();
        lblDamageBloque = new javax.swing.JLabel();
        txtFldLifeBloque = new javax.swing.JTextField();
        lblLifeBloque = new javax.swing.JLabel();
        lblBloqueImageOutput1 = new javax.swing.JLabel();
        lblImageBloque2 = new javax.swing.JLabel();
        txtFldImageBloque2 = new javax.swing.JTextField();
        txtFldImageBloque1 = new javax.swing.JTextField();
        lblImageBloque1 = new javax.swing.JLabel();
        txtFldNameBloque = new javax.swing.JTextField();
        lblNameBloque = new javax.swing.JLabel();
        pnlArmas = new javax.swing.JPanel();
        lblArmasImageOutput1 = new javax.swing.JLabel();
        lblImageArmas1 = new javax.swing.JLabel();
        lblImageArmas2 = new javax.swing.JLabel();
        lblNameArmas = new javax.swing.JLabel();
        lblLifeArmas = new javax.swing.JLabel();
        lblTypeArmas = new javax.swing.JLabel();
        lblDamageArmas = new javax.swing.JLabel();
        lblFieldsArmas = new javax.swing.JLabel();
        lblAppearanceArmas = new javax.swing.JLabel();
        lblRangeArmas = new javax.swing.JLabel();
        txtFldImageArmas1 = new javax.swing.JTextField();
        txtFldImageArmas2 = new javax.swing.JTextField();
        txtFldDamageArmas = new javax.swing.JTextField();
        txtFldLifeArmas = new javax.swing.JTextField();
        txtFldFieldsArmas = new javax.swing.JTextField();
        txtFldAppearanceArmas = new javax.swing.JTextField();
        txtFldRangeArmas = new javax.swing.JTextField();
        txtFldNameArmas = new javax.swing.JTextField();
        cmbBxTypeArmas = new javax.swing.JComboBox<>();
        lblArmasImageOutput2 = new javax.swing.JLabel();
        btnCrearArmas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbdPnCrearComponente.setBackground(new java.awt.Color(153, 153, 255));
        tbdPnCrearComponente.setOpaque(true);

        pnlZombie.setBackground(new java.awt.Color(204, 204, 204));

        btnCrearZombie.setText("Crear");

        txtFldRangeZombie.setBackground(new java.awt.Color(153, 153, 153));

        lblRangeZombie.setBackground(new java.awt.Color(102, 102, 102));
        lblRangeZombie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRangeZombie.setText("Range:");
        lblRangeZombie.setOpaque(true);

        lblAppearanceZombie.setBackground(new java.awt.Color(102, 102, 102));
        lblAppearanceZombie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppearanceZombie.setText("Appearance:");
        lblAppearanceZombie.setOpaque(true);

        txtFldAppearanceZombie.setBackground(new java.awt.Color(153, 153, 153));

        lblZombieImageOutput2.setBackground(new java.awt.Color(204, 204, 255));
        lblZombieImageOutput2.setOpaque(true);

        lblFieldsZombie.setBackground(new java.awt.Color(102, 102, 102));
        lblFieldsZombie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFieldsZombie.setText("Fields:");
        lblFieldsZombie.setOpaque(true);

        txtFldFieldsZombie.setBackground(new java.awt.Color(153, 153, 153));

        txtFldDamageZombie.setBackground(new java.awt.Color(153, 153, 153));

        lblDamageZombie.setBackground(new java.awt.Color(102, 102, 102));
        lblDamageZombie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDamageZombie.setText("Damage:");
        lblDamageZombie.setOpaque(true);

        cmbBxTypeZombie.setBackground(new java.awt.Color(153, 153, 153));
        cmbBxTypeZombie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De Contacto", "Mediano Alcance", "Aereos", "Impacto", "Ataque Multiple" }));
        cmbBxTypeZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxTypeZombieActionPerformed(evt);
            }
        });

        lblTypeZombie.setBackground(new java.awt.Color(102, 102, 102));
        lblTypeZombie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTypeZombie.setText("Type:");
        lblTypeZombie.setOpaque(true);

        txtFldLifeZombie.setBackground(new java.awt.Color(153, 153, 153));

        lblLifeZombie.setBackground(new java.awt.Color(102, 102, 102));
        lblLifeZombie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLifeZombie.setText("Life:");
        lblLifeZombie.setOpaque(true);

        lblZombieImageOutput1.setBackground(new java.awt.Color(204, 204, 255));
        lblZombieImageOutput1.setOpaque(true);

        lblImageZombie2.setBackground(new java.awt.Color(102, 102, 102));
        lblImageZombie2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageZombie2.setText("Imagen 2:");
        lblImageZombie2.setOpaque(true);

        txtFldImageZombie2.setBackground(new java.awt.Color(153, 153, 153));

        txtFldImageZombie1.setBackground(new java.awt.Color(153, 153, 153));

        lblImageZombie1.setBackground(new java.awt.Color(102, 102, 102));
        lblImageZombie1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageZombie1.setText("Imagen 1:");
        lblImageZombie1.setOpaque(true);

        txtFldZombie.setBackground(new java.awt.Color(153, 153, 153));
        txtFldZombie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldZombieActionPerformed(evt);
            }
        });

        lblNameZombie.setBackground(new java.awt.Color(102, 102, 102));
        lblNameZombie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameZombie.setText("Name:");
        lblNameZombie.setOpaque(true);

        javax.swing.GroupLayout pnlZombieLayout = new javax.swing.GroupLayout(pnlZombie);
        pnlZombie.setLayout(pnlZombieLayout);
        pnlZombieLayout.setHorizontalGroup(
            pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZombieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblZombieImageOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblZombieImageOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlZombieLayout.createSequentialGroup()
                        .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlZombieLayout.createSequentialGroup()
                                .addComponent(lblImageZombie1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFldImageZombie1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlZombieLayout.createSequentialGroup()
                                .addComponent(lblImageZombie2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFldImageZombie2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlZombieLayout.createSequentialGroup()
                                .addComponent(lblLifeZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFldLifeZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)))
                        .addGap(75, 75, 75))
                    .addGroup(pnlZombieLayout.createSequentialGroup()
                        .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlZombieLayout.createSequentialGroup()
                                .addComponent(lblTypeZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbBxTypeZombie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlZombieLayout.createSequentialGroup()
                                .addComponent(lblAppearanceZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFldAppearanceZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlZombieLayout.createSequentialGroup()
                                    .addComponent(lblDamageZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFldDamageZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlZombieLayout.createSequentialGroup()
                                    .addComponent(lblFieldsZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFldFieldsZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlZombieLayout.createSequentialGroup()
                        .addComponent(lblRangeZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFldRangeZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
            .addGroup(pnlZombieLayout.createSequentialGroup()
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlZombieLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblNameZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFldZombie, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlZombieLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btnCrearZombie)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlZombieLayout.setVerticalGroup(
            pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlZombieLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImageZombie1)
                    .addComponent(txtFldImageZombie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImageZombie2)
                    .addComponent(txtFldImageZombie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLifeZombie)
                    .addComponent(txtFldLifeZombie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeZombie)
                    .addComponent(cmbBxTypeZombie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDamageZombie)
                    .addComponent(txtFldDamageZombie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFieldsZombie)
                    .addComponent(txtFldFieldsZombie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppearanceZombie)
                    .addComponent(txtFldAppearanceZombie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRangeZombie)
                    .addComponent(txtFldRangeZombie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnCrearZombie)
                .addContainerGap())
            .addGroup(pnlZombieLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameZombie)
                    .addComponent(txtFldZombie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(lblZombieImageOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(lblZombieImageOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbdPnCrearComponente.addTab("Zombie", pnlZombie);

        pnlBloque.setBackground(new java.awt.Color(204, 204, 204));

        btnCrearBloque.setText("Crear");

        lblAppearanceBloque.setBackground(new java.awt.Color(102, 102, 102));
        lblAppearanceBloque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppearanceBloque.setText("Appearance:");
        lblAppearanceBloque.setOpaque(true);

        txtFldAppearanceBloque.setBackground(new java.awt.Color(153, 153, 153));

        lblBloqueImageOutput2.setBackground(new java.awt.Color(204, 204, 255));
        lblBloqueImageOutput2.setOpaque(true);

        lblFieldsBloque.setBackground(new java.awt.Color(102, 102, 102));
        lblFieldsBloque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFieldsBloque.setText("Fields:");
        lblFieldsBloque.setOpaque(true);

        txtFldFieldsBloque.setBackground(new java.awt.Color(153, 153, 153));

        txtFldDamageBloque.setBackground(new java.awt.Color(153, 153, 153));

        lblDamageBloque.setBackground(new java.awt.Color(102, 102, 102));
        lblDamageBloque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDamageBloque.setText("Damage:");
        lblDamageBloque.setOpaque(true);

        txtFldLifeBloque.setBackground(new java.awt.Color(153, 153, 153));

        lblLifeBloque.setBackground(new java.awt.Color(102, 102, 102));
        lblLifeBloque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLifeBloque.setText("Life:");
        lblLifeBloque.setOpaque(true);

        lblBloqueImageOutput1.setBackground(new java.awt.Color(204, 204, 255));
        lblBloqueImageOutput1.setOpaque(true);

        lblImageBloque2.setBackground(new java.awt.Color(102, 102, 102));
        lblImageBloque2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageBloque2.setText("Imagen 2:");
        lblImageBloque2.setOpaque(true);

        txtFldImageBloque2.setBackground(new java.awt.Color(153, 153, 153));

        txtFldImageBloque1.setBackground(new java.awt.Color(153, 153, 153));

        lblImageBloque1.setBackground(new java.awt.Color(102, 102, 102));
        lblImageBloque1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageBloque1.setText("Imagen 1:");
        lblImageBloque1.setOpaque(true);

        txtFldNameBloque.setBackground(new java.awt.Color(153, 153, 153));
        txtFldNameBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldNameBloqueActionPerformed(evt);
            }
        });

        lblNameBloque.setBackground(new java.awt.Color(102, 102, 102));
        lblNameBloque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameBloque.setText("Name:");
        lblNameBloque.setOpaque(true);

        javax.swing.GroupLayout pnlBloqueLayout = new javax.swing.GroupLayout(pnlBloque);
        pnlBloque.setLayout(pnlBloqueLayout);
        pnlBloqueLayout.setHorizontalGroup(
            pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBloqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBloqueImageOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBloqueImageOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBloqueLayout.createSequentialGroup()
                        .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlBloqueLayout.createSequentialGroup()
                                .addComponent(lblImageBloque1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFldImageBloque1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBloqueLayout.createSequentialGroup()
                                .addComponent(lblImageBloque2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFldImageBloque2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBloqueLayout.createSequentialGroup()
                                .addComponent(lblLifeBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFldLifeBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)))
                        .addGap(75, 75, 75))
                    .addGroup(pnlBloqueLayout.createSequentialGroup()
                        .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBloqueLayout.createSequentialGroup()
                                .addComponent(lblDamageBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFldDamageBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBloqueLayout.createSequentialGroup()
                                .addComponent(lblFieldsBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFldFieldsBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBloqueLayout.createSequentialGroup()
                                .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCrearBloque)
                                    .addComponent(lblAppearanceBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFldAppearanceBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlBloqueLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblNameBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFldNameBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBloqueLayout.setVerticalGroup(
            pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBloqueLayout.createSequentialGroup()
                .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBloqueLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImageBloque1)
                            .addComponent(txtFldImageBloque1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblImageBloque2)
                            .addComponent(txtFldImageBloque2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLifeBloque)
                            .addComponent(txtFldLifeBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDamageBloque)
                            .addComponent(txtFldDamageBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFieldsBloque)
                            .addComponent(txtFldFieldsBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAppearanceBloque)
                            .addComponent(txtFldAppearanceBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(pnlBloqueLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlBloqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameBloque)
                            .addComponent(txtFldNameBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(lblBloqueImageOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(lblBloqueImageOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnCrearBloque)
                .addGap(37, 37, 37))
        );

        tbdPnCrearComponente.addTab("Casillas", pnlBloque);

        pnlArmas.setBackground(new java.awt.Color(204, 204, 204));

        lblArmasImageOutput1.setBackground(new java.awt.Color(204, 204, 255));
        lblArmasImageOutput1.setOpaque(true);

        lblImageArmas1.setBackground(new java.awt.Color(102, 102, 102));
        lblImageArmas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageArmas1.setText("Imagen 1:");
        lblImageArmas1.setOpaque(true);

        lblImageArmas2.setBackground(new java.awt.Color(102, 102, 102));
        lblImageArmas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageArmas2.setText("Imagen 2:");
        lblImageArmas2.setOpaque(true);

        lblNameArmas.setBackground(new java.awt.Color(102, 102, 102));
        lblNameArmas.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        lblNameArmas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameArmas.setText("Name:");
        lblNameArmas.setOpaque(true);

        lblLifeArmas.setBackground(new java.awt.Color(102, 102, 102));
        lblLifeArmas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLifeArmas.setText("Life:");
        lblLifeArmas.setOpaque(true);

        lblTypeArmas.setBackground(new java.awt.Color(102, 102, 102));
        lblTypeArmas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTypeArmas.setText("Type:");
        lblTypeArmas.setOpaque(true);

        lblDamageArmas.setBackground(new java.awt.Color(102, 102, 102));
        lblDamageArmas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDamageArmas.setText("Damage:");
        lblDamageArmas.setOpaque(true);

        lblFieldsArmas.setBackground(new java.awt.Color(102, 102, 102));
        lblFieldsArmas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFieldsArmas.setText("Fields:");
        lblFieldsArmas.setOpaque(true);

        lblAppearanceArmas.setBackground(new java.awt.Color(102, 102, 102));
        lblAppearanceArmas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAppearanceArmas.setText("Appearance:");
        lblAppearanceArmas.setOpaque(true);

        lblRangeArmas.setBackground(new java.awt.Color(102, 102, 102));
        lblRangeArmas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRangeArmas.setText("Range:");
        lblRangeArmas.setOpaque(true);

        txtFldImageArmas1.setBackground(new java.awt.Color(153, 153, 153));

        txtFldImageArmas2.setBackground(new java.awt.Color(153, 153, 153));

        txtFldDamageArmas.setBackground(new java.awt.Color(153, 153, 153));

        txtFldLifeArmas.setBackground(new java.awt.Color(153, 153, 153));

        txtFldFieldsArmas.setBackground(new java.awt.Color(153, 153, 153));

        txtFldAppearanceArmas.setBackground(new java.awt.Color(153, 153, 153));

        txtFldRangeArmas.setBackground(new java.awt.Color(153, 153, 153));

        txtFldNameArmas.setBackground(new java.awt.Color(153, 153, 153));
        txtFldNameArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldNameArmasActionPerformed(evt);
            }
        });

        cmbBxTypeArmas.setBackground(new java.awt.Color(153, 153, 153));
        cmbBxTypeArmas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De Contacto", "Mediano Alcance", "Aereos", "Impacto", "Ataque Multiple" }));
        cmbBxTypeArmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxTypeArmasActionPerformed(evt);
            }
        });

        lblArmasImageOutput2.setBackground(new java.awt.Color(204, 204, 255));
        lblArmasImageOutput2.setOpaque(true);

        btnCrearArmas.setText("Crear");

        javax.swing.GroupLayout pnlArmasLayout = new javax.swing.GroupLayout(pnlArmas);
        pnlArmas.setLayout(pnlArmasLayout);
        pnlArmasLayout.setHorizontalGroup(
            pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArmasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblArmasImageOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArmasImageOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlArmasLayout.createSequentialGroup()
                        .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlArmasLayout.createSequentialGroup()
                                .addComponent(lblImageArmas1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFldImageArmas1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlArmasLayout.createSequentialGroup()
                                .addComponent(lblImageArmas2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFldImageArmas2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlArmasLayout.createSequentialGroup()
                                .addComponent(lblLifeArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFldLifeArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)))
                        .addGap(75, 75, 75))
                    .addGroup(pnlArmasLayout.createSequentialGroup()
                        .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlArmasLayout.createSequentialGroup()
                                .addComponent(lblTypeArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbBxTypeArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlArmasLayout.createSequentialGroup()
                                .addComponent(lblAppearanceArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFldAppearanceArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlArmasLayout.createSequentialGroup()
                                    .addComponent(lblDamageArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFldDamageArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlArmasLayout.createSequentialGroup()
                                    .addComponent(lblFieldsArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFldFieldsArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlArmasLayout.createSequentialGroup()
                        .addComponent(lblRangeArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFldRangeArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
            .addGroup(pnlArmasLayout.createSequentialGroup()
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlArmasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblNameArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFldNameArmas, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlArmasLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btnCrearArmas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlArmasLayout.setVerticalGroup(
            pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlArmasLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImageArmas1)
                    .addComponent(txtFldImageArmas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImageArmas2)
                    .addComponent(txtFldImageArmas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLifeArmas)
                    .addComponent(txtFldLifeArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeArmas)
                    .addComponent(cmbBxTypeArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDamageArmas)
                    .addComponent(txtFldDamageArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFieldsArmas)
                    .addComponent(txtFldFieldsArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppearanceArmas)
                    .addComponent(txtFldAppearanceArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRangeArmas)
                    .addComponent(txtFldRangeArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnCrearArmas)
                .addContainerGap())
            .addGroup(pnlArmasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlArmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameArmas)
                    .addComponent(txtFldNameArmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(lblArmasImageOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(lblArmasImageOutput2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbdPnCrearComponente.addTab("Armas", pnlArmas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdPnCrearComponente, javax.swing.GroupLayout.PREFERRED_SIZE, 464, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbdPnCrearComponente)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBxTypeArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxTypeArmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBxTypeArmasActionPerformed

    private void txtFldNameArmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldNameArmasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldNameArmasActionPerformed

    private void cmbBxTypeZombieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxTypeZombieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBxTypeZombieActionPerformed

    private void txtFldZombieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldZombieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldZombieActionPerformed

    private void txtFldNameBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldNameBloqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldNameBloqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CrearComponentes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearArmas;
    private javax.swing.JButton btnCrearBloque;
    private javax.swing.JButton btnCrearZombie;
    private javax.swing.JComboBox<String> cmbBxTypeArmas;
    private javax.swing.JComboBox<String> cmbBxTypeZombie;
    private javax.swing.JLabel lblAppearanceArmas;
    private javax.swing.JLabel lblAppearanceBloque;
    private javax.swing.JLabel lblAppearanceZombie;
    private javax.swing.JLabel lblArmasImageOutput1;
    private javax.swing.JLabel lblArmasImageOutput2;
    private javax.swing.JLabel lblBloqueImageOutput1;
    private javax.swing.JLabel lblBloqueImageOutput2;
    private javax.swing.JLabel lblDamageArmas;
    private javax.swing.JLabel lblDamageBloque;
    private javax.swing.JLabel lblDamageZombie;
    private javax.swing.JLabel lblFieldsArmas;
    private javax.swing.JLabel lblFieldsBloque;
    private javax.swing.JLabel lblFieldsZombie;
    private javax.swing.JLabel lblImageArmas1;
    private javax.swing.JLabel lblImageArmas2;
    private javax.swing.JLabel lblImageBloque1;
    private javax.swing.JLabel lblImageBloque2;
    private javax.swing.JLabel lblImageZombie1;
    private javax.swing.JLabel lblImageZombie2;
    private javax.swing.JLabel lblLifeArmas;
    private javax.swing.JLabel lblLifeBloque;
    private javax.swing.JLabel lblLifeZombie;
    private javax.swing.JLabel lblNameArmas;
    private javax.swing.JLabel lblNameBloque;
    private javax.swing.JLabel lblNameZombie;
    private javax.swing.JLabel lblRangeArmas;
    private javax.swing.JLabel lblRangeZombie;
    private javax.swing.JLabel lblTypeArmas;
    private javax.swing.JLabel lblTypeZombie;
    private javax.swing.JLabel lblZombieImageOutput1;
    private javax.swing.JLabel lblZombieImageOutput2;
    private javax.swing.JPanel pnlArmas;
    private javax.swing.JPanel pnlBloque;
    private javax.swing.JPanel pnlZombie;
    private javax.swing.JTabbedPane tbdPnCrearComponente;
    private javax.swing.JTextField txtFldAppearanceArmas;
    private javax.swing.JTextField txtFldAppearanceBloque;
    private javax.swing.JTextField txtFldAppearanceZombie;
    private javax.swing.JTextField txtFldDamageArmas;
    private javax.swing.JTextField txtFldDamageBloque;
    private javax.swing.JTextField txtFldDamageZombie;
    private javax.swing.JTextField txtFldFieldsArmas;
    private javax.swing.JTextField txtFldFieldsBloque;
    private javax.swing.JTextField txtFldFieldsZombie;
    private javax.swing.JTextField txtFldImageArmas1;
    private javax.swing.JTextField txtFldImageArmas2;
    private javax.swing.JTextField txtFldImageBloque1;
    private javax.swing.JTextField txtFldImageBloque2;
    private javax.swing.JTextField txtFldImageZombie1;
    private javax.swing.JTextField txtFldImageZombie2;
    private javax.swing.JTextField txtFldLifeArmas;
    private javax.swing.JTextField txtFldLifeBloque;
    private javax.swing.JTextField txtFldLifeZombie;
    private javax.swing.JTextField txtFldNameArmas;
    private javax.swing.JTextField txtFldNameBloque;
    private javax.swing.JTextField txtFldRangeArmas;
    private javax.swing.JTextField txtFldRangeZombie;
    private javax.swing.JTextField txtFldZombie;
    // End of variables declaration//GEN-END:variables
}
