/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thewalkingtec.poo;

import com.mycompany.thewalkingtec.poo.Terreno.Casilla;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author kyup
 */
public class fPrincipal extends javax.swing.JFrame {
    
    private ArrayList<Casilla> terreno = new ArrayList<Casilla>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fPrincipal.class.getName());

    /**
     * Creates new form fPrincipal
     */
    public fPrincipal() {
        initComponents();
        generarTerreno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTerreno = new javax.swing.JPanel();
        pnlUtilidades = new javax.swing.JPanel();
        tbPnlComponentes = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1170, 790));
        setPreferredSize(new java.awt.Dimension(1170, 790));
        setResizable(false);
        setSize(new java.awt.Dimension(1170, 790));

        pnlTerreno.setBackground(new java.awt.Color(153, 255, 153));
        pnlTerreno.setMinimumSize(new java.awt.Dimension(790, 750));
        pnlTerreno.setPreferredSize(new java.awt.Dimension(750, 750));

        javax.swing.GroupLayout pnlTerrenoLayout = new javax.swing.GroupLayout(pnlTerreno);
        pnlTerreno.setLayout(pnlTerrenoLayout);
        pnlTerrenoLayout.setHorizontalGroup(
            pnlTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTerrenoLayout.setVerticalGroup(
            pnlTerrenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        pnlUtilidades.setBackground(new java.awt.Color(255, 255, 204));
        pnlUtilidades.setMinimumSize(new java.awt.Dimension(400, 760));
        pnlUtilidades.setPreferredSize(new java.awt.Dimension(400, 750));

        tbPnlComponentes.setBackground(new java.awt.Color(255, 255, 102));
        tbPnlComponentes.setOpaque(true);

        txaLog.setColumns(20);
        txaLog.setRows(5);
        jScrollPane1.setViewportView(txaLog);

        javax.swing.GroupLayout pnlUtilidadesLayout = new javax.swing.GroupLayout(pnlUtilidades);
        pnlUtilidades.setLayout(pnlUtilidadesLayout);
        pnlUtilidadesLayout.setHorizontalGroup(
            pnlUtilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtilidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUtilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addComponent(tbPnlComponentes))
                .addContainerGap())
        );
        pnlUtilidadesLayout.setVerticalGroup(
            pnlUtilidadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtilidadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbPnlComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUtilidades, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTerreno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlUtilidades, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fPrincipal().setVisible(true));
    }
    
     private void generarTerreno(){
        //Tomar el tamaño del ejercito a agregar
        int tamano = 25;
        int x = 0;
        int y = 0;
        for (int i = 0; i < tamano; i++){
            for (int j = 0; j < tamano; j++) {
                //Para cada soldado se crea un Label
                JLabel nuevoLabel = new JLabel("");
                nuevoLabel.setOpaque(true);
                nuevoLabel.setBackground(new java.awt.Color(66, 245, 66));
                Border lineBorder = BorderFactory.createLineBorder(Color.BLACK, 2); 
                nuevoLabel.setBorder(lineBorder); // Apply the border to the label
                nuevoLabel.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e){
                        JOptionPane.showMessageDialog(pnlTerreno, ("Label Clicked" + nuevoLabel.getLocation().getX() + ", " + nuevoLabel.getLocation().getY()));
                        txaLog.append("Se clickeó sobre: X: " + nuevoLabel.getLocation().getX() + ",Y: " + nuevoLabel.getLocation().getY()+"\n");
                    }
                    
                    @Override
                    public void mouseEntered(MouseEvent e) {
                        nuevoLabel.setBackground(new java.awt.Color(245, 66, 66));
                    }
                    
                    @Override
                    public void mouseExited(MouseEvent e) {
                        nuevoLabel.setBackground(new java.awt.Color(66, 245, 66));
                    }
                
                });

                nuevoLabel.setBounds(x, y, 30, 30);

                pnlTerreno.add(nuevoLabel);
                this.terreno.add(new Casilla(nuevoLabel.getLocation(), nuevoLabel));
                
                y += 30;
            }
            y = 0;
            x += 30;
        }
        
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlTerreno;
    private javax.swing.JPanel pnlUtilidades;
    private javax.swing.JTabbedPane tbPnlComponentes;
    private javax.swing.JTextArea txaLog;
    // End of variables declaration//GEN-END:variables
}
